version: '3.1'

services:
  web:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./host.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php

#  redis:
#    image: redis

  php:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/code
    links:
      - db
#      - redis

  db:
    restart: always
    container_name: database_educa
    image: mariadb:latest
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_DATABASE=students_docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker

  composer:
    image: composer:latest
    command: install -vvv
    volumes:
      - ./:/app

